
From HB Require Import structures.
From mathcomp Require Import boot order algebra.
#[warning="-warn-library-file-internal-analysis"]
From mathcomp Require Import unstable.
From mathcomp Require Import boolp classical_sets.
From mathcomp Require Import fsbigop functions reals topology separation_axioms.
From mathcomp Require Import ereal sequences numfun measure measurable_realfun.
From mathcomp Require Import lebesgue_measure lebesgue_integral.
    
(**md**************************************************************************)
(* # The Giry monad                                                           *)
(*                                                                            *)
(* ```                                                                        *)
(*         m1 ≡μ m2 == m1 S = m2 S for any measurable set S                   *)
(*         giry T R == the type of subprobability measures over T             *)
(*      giry_ev P A == the evaluation map `giryM T R -> [0, 1]`               *)
(* preimg_giry_ev A == preimage of the sigma-algebra of extended real numbers *)
(*                     via the function giry_ev ^~ A                          *)
(*  giry_measurable == the sigma-algebra generated by the countable unions of *)
(*                     preimg_giry_ev                                         *)
(*     giry_display == display of giry_measurable                             *)
(*    giry_int mu f := \int[mu]_x f x                                         *)
(*      giry_map mf == the map of type giry T1 R -> giry T2 R                 *)
(*                     where mf is a proof that f : T1 -> T2 is measurable    *)
(*       giry_ret x == the unit of the Giry monad, i.e., \d_x                 *)
(* @giry_join _ T R == the multiplication of the Giry monad                   *)
(*                     type : giry (giry T R) R -> giry T R                   *)
(*  giry_bind mu mf == the bind with mu : giry T1 R and f : T1 -> giry T2 R   *)
(*  giry_tensorator == product of type                                        *)
(*                     giry T1 R * giry T2 R -> giry (T1 * T2) R              *)
(* ```                                                                        *)
(*                                                                            *)
(******************************************************************************)

Reserved Notation "m >>= f" (at level 49).

Unset SsrOldRewriteGoalsOrder.  (* remove the line when requiring MathComp >= 2.6 *)
Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Import Order.TTheory GRing.Theory Num.Def Num.Theory.
Import HBNNSimple MeasurableR.

(*********************)
HB.mixin Record isMeasurableSet (d : measure_display) (T : measurableType d) (A : set T) :={
  mset_is_measurable : measurable A
}.

#[short(type="mset")]
HB.structure Definition MeasurableSet d T := { A of isMeasurableSet d T A }.

Arguments mset_is_measurable {d T}.

Definition mset_of {d : measure_display} (T : measurableType d) (A : set T) (m : measurable A) : mset T :=
  MeasurableSet.Pack (MeasurableSet.Class (isMeasurableSet.Build d T A m)).

Section mset.
Variable d : measure_display.
Variable T : measurableType d.

Local Open Scope classical_set_scope.

Lemma msetT_measurable : [set: mset T] = measurable.
apply seteqP.
split => x //= _.
by exact: mset_is_measurable.
Qed.

Lemma mset_eta (C : mset T) :
  mset_of (mset_is_measurable C) = C.
  rewrite /mset_of /mset_is_measurable.
  case C => [] s [] /= [] /= z.
  congr (_ _).
Qed.
End mset.

Section mset_instances.
Local Open Scope classical_set_scope.
Variables (d1 d2 : measure_display) (T1 : measurableType d1) (T2 : measurableType d2).

(*********************)
Section Empty_is_mset_instance.
HB.instance Definition _  :=
  isMeasurableSet.Build _ _ set0 (@measurable0 d1 T1).
End Empty_is_mset_instance.

(*********************)
Section Total_is_mset_instance.
HB.instance Definition _  :=
  isMeasurableSet.Build _ _ setT (@measurableT d1 T1).
End Total_is_mset_instance.

(*********************)
Section Preimage_of_mset_is_mset_instance.
Variable (f : {mfun T1 >-> T2}) (A : mset T2).

Let mfunP : measurable (f @^-1` A).
Proof.
have := measurable_funPT f measurableT A (mset_is_measurable A).
by rewrite setTI.
Qed.
HB.instance Definition _ := isMeasurableSet.Build _ _ (f @^-1` A) mfunP.
End Preimage_of_mset_is_mset_instance.

(*********************)
Section R_singleton_is_mset_instance.
HB.instance Definition _ (R : realType) (r : R) :=
  isMeasurableSet.Build _ _ [set r] (measurable_set1 r).
End R_singleton_is_mset_instance.

(*********************)
Section Product_of_mset_is_mset_instance.
Variable (A : mset T1) (B : mset T2).

HB.instance Definition _ :=
  isMeasurableSet.Build _ _ (A `*` B)
    (measurableX (mset_is_measurable A) (mset_is_measurable B)).
End Product_of_mset_is_mset_instance.

End mset_instances.

Section TheSubprobabilitymeasure.
  Variable d : measure_display.
  Variable T : measurableType d.
  Variable A : mset T.
  Variable R : realType.
  Definition ext (mu : mset T -> \bar R) (A : set T) : \bar R :=
    if pselect (measurable A) is left H
    then mu (mset_of H) else 0%:E.
  Definition rest (mu : set T -> \bar R) (A : mset T) : \bar R :=
    mu A.
End TheSubprobabilitymeasure.

HB.mixin Record isTheSubProbability d (T : measurableType d) (R : realType)
  (mu : mset T -> \bar R) := {
    ext_mu : @subprobability d T R;
    eq_ext : @ext d T R mu = ext_mu
  }.

#[short(type=thesubprobability)]
HB.structure Definition TheSubProbability d (T : measurableType d) (R : realType)
  := {mu of isTheSubProbability d T R mu }.

Arguments ext_mu {d T R}.

(* Coercion ext_mu : thesubprobability >-> subprobability. *)

(*********************)

Local Open Scope classical_set_scope.
Local Open Scope ereal_scope.

Lemma g_sigma_algebraSP {T : Type} (X Y : set_system T) :
  sigma_algebra [set: T] Y ->
  <<s X >> `<=` Y <-> X `<=` Y.
Proof.
move=> sY; split=> [sXY|]; last exact: smallest_sub.
by rewrite {sY}; apply: subset_trans sXY; exact: sub_gen_smallest.
Qed.

Section rect_cross_prop.
Context {T1 T2 T3 : pointedType}.

Lemma preimage_smallest_sigma_algebra (Y : set_system T2) :
  preimage_set_system [set: T1 * T2] snd (<<s Y>>) =
  <<s preimage_set_system [set: T1 * T2] snd Y>>.
Proof.
apply/seteqP; split; last first.
  apply/(g_sigma_algebraSP _ _).2.
    set RY := @g_sigma_algebraType _ Y.
    exact: sigma_algebra_preimage.
  apply: preimage_set_systemS.
  exact: sub_sigma_algebra.
move=> _ [Z RYZ <-] /= G [sigG HG].
pose i := @image_set_system _ T2 setT (@snd _ _) G.
(* TODO: use image_set_system *)
apply: (RYZ i).
split.
  exact: sigma_algebra_image.
move=> A YA.
apply: HG => //.
by exists A.
Qed.

End rect_cross_prop.

Section rect_cross_prop2.
Context {T1 T2 T3 : choiceType}.

Lemma g_sigma_algebra_cross_rectangle (X : set_system T1) (Y : set_system T2)
    (Z : set_system T3) :
  X [set: T1] -> Y [set: T2] -> Z [set: T3] ->
  <<s (X `x` <<s Y `x` Z >>) >> = <<s rectangle X (rectangle Y Z) >>.
Proof.
move=> mX mY mZ; rewrite -(g_sigma_algebra_rectangle mY mZ).
rewrite g_sigma_algebra_cross -(g_sigma_algebra_rectangle mX)//= -setXTT.
exact: rectangle_setX.
Qed.

End rect_cross_prop2.

(* TODO: move *)

Definition fun_pair {X T1 T2} (f : X -> T1) (g : X -> T2)
  (x : X) := (f x, g x).

Lemma preimage_fun_pair {X T1 T2} (f : X -> T1) (g : X -> T2) A B :
  (fun_pair f g) @^-1` (A `*` B) = f @^-1` A `&` g @^-1` B.
Proof. by []. Qed.

Lemma prodA_fun_pair {X Y Z} :
  @prodA X Y Z = fun_pair (fst \o fst) (fun_pair (snd \o fst) snd).
Proof. by apply/funext => -[[]]. Qed.

Definition fun_product {T1 T2 T1' T2'} (f : T1 -> T1') (g : T2 -> T2')
  (xy : T1 * T2) := (f xy.1, g xy.2).

Reserved Notation "f '\X' g" (at level 40, left associativity).
Notation "f '\X' g" := (fun_product f g) : classical_set_scope.

Lemma preimage_setX (T1 T1' T2 T2' : Type) (A : set T1') (B : set T2')
    (f : T1 -> T1') (g : T2 -> T2') :
  (f \X g) @^-1` (A `*` B) = f @^-1` A `*` g @^-1` B.
Proof. by apply/seteqP; split=> []. Qed.

Section fun_product.
Context {d1} {d2} {X : measurableType d1} {Y : measurableType d2}
  {d1'} {d2'} {X' : measurableType d1'} {Y' : measurableType d2'}
  {R : realType}.
Variables (f : {mfun X >-> X'}) (g : {mfun Y >-> Y'}).

Let measurable_fun_product : measurable_fun [set: X * Y] (f \X g).
Proof. by apply: measurable_fun_pair => /=; exact: measurableT_comp. Qed.

HB.instance Definition _ := isMeasurableFun.Build _ _ _ _
  (f \X g) measurable_fun_product.

HB.instance Definition _ :=
  isMeasurableFun.Build _ _ _ _ snd (@measurable_snd _ _ X Y).

HB.instance Definition _ :=
  isMeasurableFun.Build _ _ _ _ fst (@measurable_fst _ _ X Y).

HB.instance Definition _  :=
  isMeasurableFun.Build _ _ _ _ idfun (@measurable_id d1 X setT).
End fun_product.

Section prodA_measurable.
Context {d1 d2 d3} {X : measurableType d1} {Y : measurableType d2}
  {Z : measurableType d3}.

Let measurable_prodA : measurable_fun [set: X * Y * Z] (@prodA X Y Z).
Proof.
apply: measurable_fun_pair => /=; first exact: measurableT_comp.
by apply: measurable_fun_pair => //=; do 2 exact: measurableT_comp.
Qed.

HB.instance Definition _ := isMeasurableFun.Build _ _ _ _
  prodA measurable_prodA.

End prodA_measurable.

Section swap_measurable.
Context {d1 d2} {X : measurableType d1} {Y : measurableType d2}.

HB.instance Definition _ := isMeasurableFun.Build _ _ _ _
  swap (@measurable_swap _ _ X Y).
End swap_measurable.

Lemma preimage_swap {T1 T2} (U1 : set T1) (U2 : set T2) :
  swap @^-1` (U1 `*` U2) = U2 `*` U1.
Proof. by rewrite /preimage; apply/seteqP; split => [[a b]|[a b]]//= []. Qed.
(* /TODO: move *)

Section giry_def.
Context d (T : measurableType d) (R : realType).

Definition giry : Type := @thesubprobability d T R.

HB.instance Definition _ := gen_eqMixin giry.
HB.instance Definition _ := gen_choiceMixin giry.
(*HB.instance Definition _ := isPointed.Build giry mzero.*)

Definition giry_ev (A : mset T) (mu : giry) := mu A.

Definition preimg_giry_ev (A : mset T) : set_system giry :=
  preimage_set_system [set: giry] (giry_ev A) measurable.

Definition giry_measurable := <<s \bigcup_(A in [set: mset T]) preimg_giry_ev A >>.

Let giry_measurable0 : giry_measurable set0.
Proof. exact: sigma_algebra0. Qed.

Let giry_measurableC (U : set giry) :
  giry_measurable U -> giry_measurable (~` U).
Proof. exact: sigma_algebraC. Qed.

Let giry_measurableU (F : (set giry)^nat) :
  (forall i, giry_measurable (F i)) -> giry_measurable (\bigcup_i F i).
Proof. exact: sigma_algebra_bigcup. Qed.

Definition giry_display : measure_display.
Proof. by constructor. Qed.

HB.instance Definition _ :=
  @isMeasurable.Build giry_display giry giry_measurable
    giry_measurable0 giry_measurableC giry_measurableU.

(*
Goal forall (F : nat -> set nat) (G : nat -> nat),
    F (G 0%N) = \bigcup_(j in [set: nat]) F (G j).
Proof.
From mathcomp Require Import ssrmatching.
move=> F G.
ssrpattern (0%N in LHS).

move=> F G.
apply: bigcup_sup.
rewrite [X in X `<=` _](_ : _ = (fun x => F x) 0%N)//.
Fail apply: bigmax_sup.
rewrite [X in X `<=` _](_ : _ = eta (fun x => F x) 0%N)//.
apply: bigmax_sup.
*)

Lemma measurable_giry_ev (A : mset T) : measurable_fun [set: giry] (giry_ev A).
Proof.
apply: (@measurability giry_display _ giry _ setT (giry_ev A) measurable).
  by rewrite smallest_id//; exact: sigma_algebra_measurable.
apply: subset_trans; last exact: sub_gen_smallest.
rewrite -/(preimg_giry_ev _).
exact: bigcup_sup.
Qed.

End giry_def.
Arguments giry_ev {d T R} A mu.

Section giry_ev_measurable.
Context d (T : measurableType d) (R : realType).
Variables (A : mset T).

HB.instance Definition _ := isMeasurableFun.Build _ _ _ _ (@giry_ev _ _ R A)
  (measurable_giry_ev A).

End giry_ev_measurable.

Section giry_integral.
Context {d} {T : measurableType d} {R : realType}.

Definition giry_int (mu : giry T R) (f : T -> \bar R) := \int[ext_mu mu]_x f x.

Lemma ext_mu_giry_ev mu (A : set T) (mA : measurable A) :
  ext_mu mu A = giry_ev (mset_of mA) mu :> \bar R.
Proof.
  rewrite -eq_ext.
  rewrite /ext.
  case:pselect => // mA'.
  rewrite /giry_ev.
  congr (mu (mset_of _)).
  exact: Prop_irrelevance.
Qed.
(**md The idea is to reconstruct f from simple functions, then use measurability
  of giry_ev. Reference: Tom Avery. Codensity and the Giry monad.
  https://arxiv.org/pdf/1410.4432.
 *)
Lemma measurable_giry_int (f : T -> \bar R) :
  measurable_fun [set: T] f -> (forall x, 0 <= f x) ->
  measurable_fun [set: giry T R] (giry_int ^~ f).
Proof.
move=> mf h0.
pose g := nnsfun_approx measurableT mf.
pose Eg := fun n => EFin \o g n.
pose intEg := fun n mu => giry_int mu (Eg n).
have mintgE n : measurable_fun [set: giry T R] (intEg n).
  rewrite /intEg /giry_int/=.
  under eq_fun do rewrite integralT_nnsfun sintegralE.
  apply: emeasurable_fsum => //= r.
  apply: measurable_funeM => /=.
  under [X in measurable_fun _ X]funext do rewrite ext_mu_giry_ev.
  exact: measurable_giry_ev.
apply: (emeasurable_fun_cvg _ (giry_int ^~ f) mintgE) => mu _.
rewrite (_ : giry_int mu f = \int[ext_mu mu]_x limn (Eg ^~ x)).
  apply: eq_integral => t _.
  by apply/esym/cvg_lim  => //; exact/cvg_nnsfun_approx.
apply: cvg_monotone_convergence => //.
- by move=> n; exact/measurable_EFinP.
- by move=> n x _; rewrite lee_fin.
- by move=> t _ n m nm; apply/lefP/nd_nnsfun_approx.
Qed.

End giry_integral.
Arguments giry_int {d T R} mu f.

Section measurable_giry_codensity.
Context d1 {T1 : measurableType d1}.

Lemma measurable_giry_codensity d2 {T2 : measurableType d2} {R : realType}
    (D : set T1) (f : T1 -> giry T2 R) :
  measurable D ->
  (forall B (mB : measurable B), measurable_fun D (f ^~ (mset_of mB))) ->
  measurable_fun D f.
Proof.
move=> mD mf.
pose G : set_system (giry T2 R) := \bigcup_(B in [set: mset T2]) preimg_giry_ev B.
apply: (measurability G) => //= _ [_ [C mC [Z mZ] <-] <-].
rewrite setTI => //=.
move: (mf C (mset_is_measurable C)) => //=.
rewrite mset_eta /measurable_fun /preimage /mkset /giry_ev //= => V.
by move:(V mD Z mZ).
Qed.

Lemma mset_giry_codensity d2 {T2 : measurableType d2} {R : realType}
    (D : set T1) (f : T1 -> giry T2 R) :
  measurable D ->
  (forall B : mset T2, measurable_fun D (f ^~ B)) ->
  measurable_fun D f.
Proof.
move=> mD mf.
pose G : set_system (giry T2 R) := \bigcup_(B in [set: mset T2]) preimg_giry_ev B.
apply: (measurability G) => //= _ [_ [C mC [Z mZ] <-] <-].
rewrite setTI.
exact: mf.
Qed.

End measurable_giry_codensity.

Section giry_map.
Context {d1} {d2} {T1 : measurableType d1} {T2 : measurableType d2}
  {R : realType}.
Variables (f : {mfun T1 >-> T2}) (mu1 : giry T1 R).

Let map := fun (U : mset T2) => mu1 (f @^-1` U).

Let map0 : map set0 = 0.
Proof.
  exact (measure0 mu1).
Qed.

Let map_ge0 A : 0 <= map A. Proof. exact: measure_ge0. Qed.

Let map_sigma_additive : semi_sigma_additive map.
Proof. exact: measure_semi_sigma_additive. Qed.

HB.instance Definition _ := isMeasure.Build _ _ _ map
  map0 map_ge0 map_sigma_additive.

(* used to work before the change of definition of pushforward
HB.instance Definition _ := Measure.on gMap_ev.
the change of definition was maybe not a good idea...
https://github.com/math-comp/analysis/pull/1661
*)

Let map_setT : map [set: T2] <= 1.
Proof. by rewrite /map /pushforward /= sprobability_setT. Qed.

HB.instance Definition _ := Measure_isSubProbability.Build _ _ _ map map_setT.

Definition giry_map : giry T2 R := map.

End giry_map.

Section giry_map_lemmas.
Context d1 d2 (T1 : measurableType d1) (T2 : measurableType d2) (R : realType).
Implicit Type f : {mfun T1 >-> T2}.

Let measurable_giry_map f : measurable_fun [set: giry T1 R] (giry_map f).
Proof.
rewrite /giry_map; apply: mset_giry_codensity => // B.
apply: measurable_giry_ev.
exact: mset_is_measurable.
Qed.

HB.instance Definition _ f := isMeasurableFun.Build _ _ _ _
  (giry_map f) (measurable_giry_map f).

Lemma giry_int_map f (mu : giry T1 R) (h : T2 -> \bar R) :
  measurable_fun [set: T2] h -> (forall x, 0 <= h x) ->
  giry_int (giry_map f mu) h = giry_int mu (h \o f).
Proof. by move=> mh h0; exact: ge0_integral_pushforward. Qed.

Lemma giry_map_dirac f (mu1 : giry T1 R) (B : set T2) : measurable B ->
  giry_map f mu1 B = \int[mu1]_x (\d_(f x))%R B.
Proof.
move=> mB.
rewrite -[in LHS](setIT B) -[LHS]integral_indic// [LHS]giry_int_map//.
exact/measurable_EFinP/measurable_indic.
Qed.

End giry_map_lemmas.

Section giry_ret.
Context {d} {T : measurableType d} {R : realType}.

Definition giry_ret (x : T) : giry T R := (\d_x)%R.

Let measurable_giry_ret : measurable_fun [set: T] giry_ret.
Proof.
by apply: measurable_giry_codensity => //; exact: measurable_fun_dirac.
Qed.

HB.instance Definition _ := isMeasurableFun.Build _ _ _ _
  giry_ret measurable_giry_ret.

Lemma giry_int_ret (x : T) (f : T -> \bar R) : measurable_fun [set: T] f ->
  giry_int (giry_ret x) f = f x.
Proof.
by move=> mf; rewrite /giry_int /giry_ret integral_dirac// diracT mul1e.
Qed.

End giry_ret.

Section giry_join.
Context {d} {T : measurableType d} {R : realType}.
Variable M : giry (giry T R) R.

Let join_mset A := giry_int M (giry_ev A).

Let join (A : set T) : \bar R :=
  if pselect (measurable A) is left H
  then join_mset (mset_of H) else 0%:E.

Lemma measurable_joinE (A : set T) (mA : measurable A) :
  join A = join_mset (mset_of mA).
Proof. by rewrite /join; case: pselect. Qed.

Let join0 : join set0 = 0.
Proof.
rewrite (measurable_joinE measurable0).
by rewrite /join_mset /giry_ev /giry_int/= integral0_eq.
Qed.

Let join_ge0 A : 0 <= join A.
Proof. by rewrite /join; case: pselect => // ?; exact: integral_ge0. Qed.

Let join_semi_sigma_additive : semi_sigma_additive join.
Proof.
move=> F mF tF mUF.
rewrite (measurable_joinE mUF).
rewrite [X in _ --> X](_ : _ = giry_int M (fun x => \sum_(0 <= k <oo) x (F k))).
  apply: eq_integral => mu _.
  by apply/esym/cvg_lim => //; exact: measure_sigma_additive.
rewrite [X in X @ _](_ : _ =
    (fun n => giry_int M (fun mu => \sum_(0 <= i < n) mu (F i)))).
  apply/funext => n.
  under eq_bigr => i do rewrite (measurable_joinE (mF i)).
  by rewrite -ge0_integral_sum.
apply: cvg_monotone_convergence => //.
- move=> n; apply: emeasurable_sum => m.
  exact: (measurable_giry_ev (mset_of _)).
- by move=> n x _; rewrite sume_ge0.
- by move=> x _ m n mn; exact: ereal_nondecreasing_series.
Qed.

HB.instance Definition _ := isMeasure.Build d _ R join
  join0 join_ge0 join_semi_sigma_additive.

Let join_setT : join [set: T] <= 1.
Proof.
rewrite (@le_trans _ _ (\int[M]_x `|giry_ev [set: T] x|))//; last first.
  rewrite (le_trans _ (@sprobability_setT _ _ _ M))//.
  rewrite -[leRHS]mul1e integral_le_bound//.
  by apply/aeW => x _; rewrite gee0_abs// sprobability_setT.
rewrite measurable_joinE ge0_le_integral//=.
- by apply: measurableT_comp => //; exact: measurable_giry_ev.
- by move=> x _; rewrite gee0_abs.
Qed.

HB.instance Definition _ := Measure_isSubProbability.Build _ _ _ join join_setT.

Definition giry_join : giry T R := locked (join : giry T R) .

Lemma giry_joinE (A : set T) (mA : measurable A) :
  giry_join A = join_mset (mset_of mA).
Proof. by rewrite /giry_join -lock /= measurable_joinE. Qed.

Lemma giry_joinE0 (A : set T) : ~ measurable A -> giry_join A = 0.
Proof. by move=> ?; rewrite /giry_join -lock/= /join; case: pselect. Qed.

End giry_join.
Arguments giry_join {d T R}.

Section measurable_giry_join.
Context {d} {T : measurableType d} {R : realType}.

Let measurable_giry_join : measurable_fun [set: giry (giry T R) R] giry_join.
Proof.
apply: measurable_giry_codensity => //= B mB.
under [X in measurable_fun _ X]funext do rewrite giry_joinE.
rewrite -/(measurable_fun _ _).
by apply: measurable_giry_int => //; exact: measurable_giry_ev.
Qed.

HB.instance Definition _ := isMeasurableFun.Build _ _ _ _
  giry_join measurable_giry_join.

Lemma sintegral_giry_join (M : giry (giry T R) R) (h : {nnsfun T >-> R}) :
  sintegral (giry_join M) h = \int[M]_mu sintegral mu h.
Proof.
under eq_integral do rewrite sintegralE.
rewrite ge0_integral_fsum//.
- by move=> r; apply: measurable_funeM; exact: measurable_giry_ev.
- by move=> n x _; exact: nnsfun_mulemu_ge0.
rewrite sintegralE /=; apply: eq_fsbigr => // r rh.
rewrite integralZl//.
have := finite_measure_integrable_cst M 1 measurableT.
apply: le_integrable => //; first exact: measurable_giry_ev.
move=> mu _ /=.
rewrite normr1 (le_trans _ (@sprobability_setT _ _ _ mu))// gee0_abs//.
  by rewrite le_measure// ?inE.
by rewrite giry_joinE.
Qed.

Lemma giry_int_join (M : giry (giry T R) R) (h : T -> \bar R) :
    measurable_fun [set: T] h -> (forall x, 0 <= h x) ->
  giry_int (giry_join M) h = giry_int M (giry_int ^~ h).
Proof.
move=> mh h0.
pose g := nnsfun_approx measurableT mh.
pose gE := fun n => EFin \o g n.
have mgE n : measurable_fun [set: T] (gE n) by exact/measurable_EFinP.
have gE_ge0 n x : 0 <= gE n x by rewrite lee_fin.
have nd_gE x : {homo gE ^~ x : n m / (n <= m)%O >-> n <= m}.
  by move=> *; exact/lefP/nd_nnsfun_approx.
rewrite /giry_int.
transitivity (limn (fun n => \int[giry_join M]_x gE n x)).
  rewrite -monotone_convergence//; apply: eq_integral => t _.
  by apply/esym/cvg_lim => //; exact: cvg_nnsfun_approx.
transitivity (limn (fun n => \int[M]_mu \int[mu]_x gE n x)).
  apply: congr_lim; apply/funext => n.
  rewrite integralT_nnsfun sintegral_giry_join; apply: eq_integral => x _.
  by rewrite integralT_nnsfun.
rewrite -[LHS]monotone_convergence//.
- by move=> n; exact: measurable_giry_int.
- by move=> n x _; exact: integral_ge0.
- by move=> x _ m n mn; apply: ge0_le_integral => // t _; exact: nd_gE.
apply: eq_integral => mu _.
rewrite -monotone_convergence//.
apply: eq_integral => t _.
by apply/cvg_lim => //; exact: cvg_nnsfun_approx.
Qed.

End measurable_giry_join.

Section giry_bind.
Context {d1} {d2} {T1 : measurableType d1} {T2 : measurableType d2}
  {R : realType}.
Implicit Types (mu : giry T1 R) (f : {mfun T1 >-> giry T2 R}).

Definition giry_bind mu f : giry T2 R := (giry_join \o giry_map f) mu.

Local Notation "m >>= f" := (giry_bind m f).

Lemma measurable_giry_bind f :
  measurable_fun [set: giry T1 R] (fun mu => mu >>= f).
Proof. exact: (@measurableT_comp _ _ _ _ _ _ _ _ (giry_map f)). Qed.

Lemma giry_int_bind mu f (h : T2 -> \bar R) :
    measurable_fun [set: T2] h -> (forall x, 0 <= h x)%E ->
  giry_int (mu >>= f) h = giry_int mu (fun x => giry_int (f x) h).
Proof.
move=> mh h0; rewrite /giry_bind /= giry_int_join// giry_int_map//.
  exact: measurable_giry_int.
by move=> ?; exact: integral_ge0.
Qed.

End giry_bind.

Section giry_monad.
Context d1 d2 d3
  (T1 : measurableType d1)
  (T2 : measurableType d2)
  (T3 : measurableType d3)
  (f : {mfun T1 >-> T2})
  (g : {mfun T2 >-> T3})
  (R : realType).

(* G id = id *)
Lemma giry_map_id (x : giry T1 R):
  giry_map idfun x ≡μ @idfun (giry T1 R) x.
Proof.
  move => U H /=.
  rewrite /pushforward.
  rewrite /preimage /=.
  exact.
Qed.

(* G (g o f) = G g o G f *)
Lemma giry_map_comp (x : giry T1 R) :
  giry_map (g \o f) x ≡μ (giry_map g \o giry_map f) x.
  move => U H /=.
  rewrite /pushforward.
  by rewrite /preimage /=.
Qed.

(* Naturality of return *)
Lemma giry_ret_natural (x : T1) :
  (giry_map f \o (@giry_ret _ _ R)) x ≡μ (giry_ret \o f) x.
Proof.
  move => U H /=.
  by rewrite /dirac /= /pushforward /indic /preimage.
Qed.

(* Naturality of join *)
Lemma giry_join_natural (x : giry (giry T1 R) R) :
  (giry_join \o giry_map (giry_map f)) x ≡μ
  (giry_map f \o giry_join) x.
Proof.
move=> X mS/=; rewrite giry_joinE giry_int_map//.
rewrite /pushforward giry_joinE//.
exact: measurable_funPTI.
Qed.

(* Left unit *)
Lemma giry_join_Mret (x : giry T1 R) :
  (giry_join \o giry_map giry_ret) x ≡μ x.
Proof.
move=> A mA/=.
rewrite giry_joinE giry_int_map//.
by rewrite /giry_int /giry_ev /giry_ret/= /dirac integral_indic// setIT.
Qed.

(* Right unit *)
Lemma giry_join_retM (x : giry T1 R) :
  (giry_join \o giry_ret) x ≡μ x.
Proof. by move=> A mA/=; rewrite giry_joinE giry_int_ret. Qed.

Lemma giry_ev_join (A : mset T1) :
  giry_ev A \o giry_join = (@giry_int _ _ R)^~ (giry_ev A).
Proof.
apply/funext => ?/=; rewrite /giry_ev/= giry_joinE//.
exact: mset_is_measurable.
Qed.

(* Associativity *)
Lemma giry_joinA (x : giry (giry (giry T1 R) R) R) :
  (giry_join \o giry_map giry_join) x ≡μ
  (giry_join \o giry_join) x.
Proof.
move=> A mA/=.
by rewrite giry_joinE giry_int_map// giry_ev_join giry_joinE giry_int_join.
Qed.
End giry_monad.

(* The unitor is ret unit in the Cartesian case*)
(* The tensorator is implemented by the product distribution construction *)
(* https://en.wikipedia.org/wiki/Giry_monad#Product_distributions  *)
Section giry_tensorator.
Definition giry_tensorator {d1} {d2} {T1 : measurableType d1} {T2 : measurableType d2}
    {R : realType} (m : giry T1 R * giry T2 R) : giry (T1 * T2)%type R :=
  @product_subprobability _ _ T1 T2 R m.
End giry_tensorator.

Section measurable_giry_tensorator.
Context {d1} {d2} {T1 : measurableType d1} {T2 : measurableType d2}
  {R : realType}.

(* See: Tobias Fritz. A synthetic approach to Markov kernels, conditional
   independence and theorems on sufficient statistics.
   https://arxiv.org/abs/1908.07021 *)
Let measurable_giry_tensorator :
  measurable_fun [set: giry T1 R * giry T2 R] giry_tensorator.
Proof.
apply: measurable_giry_codensity => //=.
rewrite prod_measurable_rectangle.
apply: dynkin_induction => /=.
- by rewrite prod_measurable_rectangle.
- move=> _ _ [A1 mA1 [A2 mA2 <-]] [B1 mB1 [B2 mB2 <-]].
  exists (A1 `&` B1); first exact: measurableI.
  exists (A2 `&` B2); first exact: measurableI.
  by rewrite setXI.
- apply: (eq_measurable_fun (fun x : giry T1 R * giry T2 R =>
      x.1 [set: T1] * x.2 [set: T2])).
    by move=> x _; rewrite -setXTT product_measure1E.
  by apply: emeasurable_funM => /=;
    apply: (@measurableT_comp _ _ _ _ _ _ (giry_ev _)) => //;
    exact: measurable_giry_ev.
- move=> _ [A mA [B mB <-]].
  apply: (eq_measurable_fun (fun x : giry T1 R * giry T2 R => x.1 A * x.2 B)).
    by move=> x _; rewrite product_measure1E.
  rewrite (_ : A = mset_of mA)// (_ : B = mset_of mB)// (lock mset_of).
  by apply: emeasurable_funM;
    apply: (@measurableT_comp _ _ _ _ _ _ (giry_ev _)).
- move=> S mS HS.
  apply: (eq_measurable_fun (fun x : giry T1 R * giry T2 R =>
      x.1 [set: T1] * x.2 [set: T2] - (x.1 \x x.2) S)).
    move=> /= x _; rewrite product_subprobability_setC//.
    by rewrite -setXTT product_measure1E.
  apply emeasurable_funB => //=.
  by apply: emeasurable_funM => //=;
    apply: (@measurableT_comp _ _ _ _ _ _ (giry_ev _)) => //;
    exact: measurable_giry_ev.
- move=> F mF tF Fn.
  apply: (eq_measurable_fun (fun x : giry T1 R * giry T2 R =>
      \sum_(0 <= k <oo) (x.1 \x x.2) (F k))).
    by move=> x _; rewrite measure_semi_bigcup//; exact: bigcup_measurable.
  exact: ge0_emeasurable_sum.
Qed.

HB.instance Definition _ := isMeasurableFun.Build _ _ _ _
  giry_tensorator measurable_giry_tensorator.

End measurable_giry_tensorator.

Section giry_tensorator_int.
Context {d1} {d2} {T1 : measurableType d1} {T2 : measurableType d2}
  {R : realType} (m1 : giry T1 R) (m2 : giry T2 R) (h : T1 * T2 -> \bar R).
Hypotheses (mh : measurable_fun [set: T1 * T2] h) (h0 : forall x, 0 <= h x).

Lemma giry_int_tensorator1 : giry_int (giry_tensorator (m1, m2)) h =
  giry_int m1 (fun x => giry_int m2 (fun y => h (x, y))).
Proof. exact: fubini_tonelli1. Qed.

Lemma giry_int_tensorator2 : giry_int (giry_tensorator (m1, m2)) h =
  giry_int m2 (fun y => giry_int m1 (fun x => h (x, y))).
Proof. exact: fubini_tonelli2. Qed.

End giry_tensorator_int.

Section giry_tensorator_axioms.
Context {d1} {d2} {X : measurableType d1} {Y : measurableType d2}
  {d1'} {d2'} {X' : measurableType d1'} {Y' : measurableType d2'}
  {R : realType}.
Variables (f : {mfun X >-> X'}) (g : {mfun Y >-> Y'}).

Lemma giry_tensorator_natural (x : giry X R * giry Y R) :
  (giry_map (f \X g) \o giry_tensorator) x ≡μ
  (giry_tensorator \o (giry_map f \X giry_map g)) x.
Proof.
move=> /= UV mUV; rewrite /giry_map /giry_tensorator /product_subprobability/=.
apply/esym/product_measure_unique => //= U V mU mV.
rewrite /pushforward preimage_setX/= product_measure1E//;
exact: measurable_funPTI.
Qed.

Lemma giry_tensoratorL (x : unit * giry Y R) :
  (giry_map snd \o (giry_tensorator \o (giry_ret \X id))) x ≡μ snd x.
Proof.
move=> /= U mU.
by rewrite /pushforward -setTX/= product_measure1E//= diracT mul1e.
Qed.

Lemma giry_tensoratorR (xi : giry X R * unit) :
  (giry_map fst \o giry_tensorator \o (id \X giry_ret)) xi ≡μ fst xi.
Proof.
move=> /= U mU.
by rewrite /pushforward -setXT/= product_measure1E//= diracT mule1.
Qed.

Lemma giry_tensoratorA (xyz : (giry X R * giry Y R) * giry Y' R) :
  (giry_tensorator \o (id \X giry_tensorator) \o prodA) xyz ≡μ
  (giry_map prodA \o giry_tensorator \o (giry_tensorator \X id)) xyz.
Proof.
move: xyz => [[x y] z].
move=> U mU.
rewrite /measurable /= /g_sigma_preimageU in mU.
have mU' :
    <<s (d1.-measurable `x` <<s (d2.-measurable `x` d2'.-measurable) >>) >> U.
  by [].
rewrite g_sigma_algebra_cross_rectangle in mU'; [exact: measurableT..|].
apply: (measure_unique (rectangle d1.-measurable
         (rectangle d2.-measurable d2'.-measurable)) (fun=> setT)) => //.
- by rewrite -g_sigma_algebra_cross_rectangle.
- apply: setI_closed_rectangle => //; first exact: measurableI.
  by apply: setI_closed_rectangle => //; exact: measurableI.
- move=> _.
  rewrite -!setXTT.
  by apply: rectangle_setX => //; exact: rectangle_setX.
- apply: bigcupT => //.
  by exists O.
- move=> A [Q mQ] [E [E1 mE1 [E2 mE2]]] <- <- /=.
  rewrite /pushforward.
  rewrite (_ : _ @^-1` _ = (Q `*` E1) `*` E2).
    by apply/seteqP; split => -[[]]/= *; tauto.
  rewrite !product_measure1E//=.
    exact: measurableX.
  rewrite (@product_measure1E _ _ _ _ _ x (product_subprobability (y, z)))//=.
    exact: measurableX.
  by rewrite !product_measure1E//= muleA.
- by rewrite ltey_eq fin_num_measure.
Qed.

Lemma giry_tensoratorS (xy : giry X R * giry Y R) :
  (giry_tensorator \o swap) xy ≡μ (giry_map swap \o giry_tensorator) xy.
Proof.
move=> U mU/=.
apply: product_measure_unique => //= U1 U2 mU1 mU2.
rewrite /pushforward.
by rewrite preimage_swap product_measure1E// muleC.
Qed.
End giry_tensorator_axioms.

Section monoidal_giry_ret_join.
Context {d1} {d2} {X : measurableType d1} {Y : measurableType d2}
  {R : realType}.
  
Lemma giry_ret_monoidal (xy : X * Y) :
  (@giry_tensorator _ _ _ _ R \o (giry_ret \X giry_ret)) xy ≡μ giry_ret xy.
Proof.
case: xy => x y.
move=> U mU/=.
apply: product_measure_unique => //= U1 U2 mU1 mU2.
rewrite !diracE.
rewrite in_setX/=.
by rewrite -EFinM -natrM mulnb.
Qed.

Lemma giry_join_monoidal (c : giry (giry X R) R * giry (giry Y R) R) :
  (giry_tensorator \o (giry_join \X giry_join)) c ≡μ
  (giry_join \o (giry_map giry_tensorator) \o giry_tensorator) c.
Proof.
case: c => a b.
move=> U mU.
rewrite /giry_tensorator (*/giry_join /giry_join*). (* NB: don't /= here*)
apply: product_measure_unique => //= A B mA mB.
have ? := measurableX mA mB.
rewrite giry_joinE// /giry_int /giry_map ge0_integral_pushforward//=.
rewrite fubini_tonelli1//=.
have mAB : measurable (A `*` B) by apply: measurableX.
  (* Check @giry_ev _ _ R (A `*` B) \o giry_tensorator  : {mfun _ >-> _}. *)
  (* giry X R * giry Y R -> GRing.BaseAddMagma.sort \bar R *)
  Check (fun z : giry X R * giry Y R => (z.1 \x z.2) (A `*` B)). 
  rewrite [X in measurable_fun _ X](_ : _ = @giry_ev _ _ R (A `*` B) \o giry_tensorator).
    by rewrite //.
  apply: measurableT_comp.
    exact: measurable_giry_ev.
  by [].  
rewrite !giry_joinE.
rewrite -ge0_integralZr//.
  exact: integral_ge0.
apply: eq_integral => /= x _.
rewrite /fubini_F/= -ge0_integralZl//.
apply: eq_integral => /= y _.
by rewrite product_measure1E.
Qed.
End monoidal_giry_ret_join.
